Imports

In [1]:
import numpy as np

Data

In [12]:
# Example with 3 samples and 3 classes

sample_1 = [2.0, 1.0, 0.1]
sample_2 = [-1.2, 3.5, -0.5]
sample_3 = [1.8, 1.5, -2.0]

logits = np.array([sample_1, sample_2, sample_3])
logits, logits.shape

(array([[ 2. ,  1. ,  0.1],
        [-1.2,  3.5, -0.5],
        [ 1.8,  1.5, -2. ]]),
 (3, 3))

In [7]:
# labels
labels_sparse = np.array([0, 1, 2])

labels_one_hot = np.array([
    [1, 0, 0],  # True class is index 0
    [0, 1, 0],  # True class is index 1
    [0, 0, 1]   # True class is index 2
])

labels_sparse.shape, labels_one_hot.shape

((3,), (3, 3))

Softmax

In [2]:
from src.modules.activations import softmax

In [15]:
probabilities = softmax(logits)
probabilities.shape

calculating the numerator = e^x for each value of x in the input tensor of scores
the nummerator is [[1.         0.36787944 0.14956862]
 [0.00909528 1.         0.01831564]
 [1.         0.74081822 0.02237077]]
calculating the denominator = summing across the last dimension of the numerator (vocab_size)
the denominator is [[1.51744806]
 [1.02741092]
 [1.76318899]]


(3, 3)

Cross-Entropy Loss

In [16]:
from src.utils.optimisation import cross_entropy_loss_one_hot, cross_entropy_loss_sparse

In [17]:
loss_one_hot = cross_entropy_loss_one_hot(probabilities, labels_one_hot)
loss_one_hot

1.6037320257364263

In [18]:
loss_sparse = cross_entropy_loss_sparse(probabilities, labels_sparse)
loss_sparse

1.6037320257364263