Imports

In [1]:
import numpy as np

Data

In [ ]:
# Example with 3 samples and 3 features

sample_1 = [2.0, 1.0, 0.1]
sample_2 = [-1.2, 3.5, -0.5]
sample_3 = [1.8, 1.5, -2.0]

input = np.array([sample_1, sample_2, sample_3])
input, input.shape

(array([[ 2. ,  1. ,  0.1],
        [-1.2,  3.5, -0.5],
        [ 1.8,  1.5, -2. ]]),
 (3, 3))

In [ ]:
# We also have 3 labels / classes
labels_sparse = np.array([0, 1, 2])

labels_one_hot = np.array([
    [1, 0, 0],  # True class is index 0
    [0, 1, 0],  # True class is index 1
    [0, 0, 1]   # True class is index 2
])

labels_sparse.shape, labels_one_hot.shape

((3,), (3, 3))

Linear Layer

In [11]:
from src.modules.feedforward import linear_layer

In [12]:
# initialize empty 3 x 3 weight matrix (mapping 3 input features to 3 output classes)
weights = np.random.randn(3, 3)
weights

array([[ 1.24357698,  0.63838419,  1.01888599],
       [ 1.36890485, -0.44435781, -0.33398344],
       [-1.8356128 , -0.02642125, -1.25734956]])

In [14]:
logits = linear_layer(input, weights)
logits

array([[ 3.55508771,  5.00625061, -2.23260637],
       [ 2.66986888, -0.68732264,  1.02703626],
       [-5.90274932, -3.81411151,  2.34434847]])

Softmax

In [15]:
from src.modules.activations import softmax

In [16]:
probabilities = softmax(logits)

calculating the numerator = e^x for each value of x in the input tensor of scores
the numerator is [[0.23429766477476083, 1.0, 0.0007181321347795867], [1.0, 0.03483294930833397, 0.1934313482704298], [0.0002620178841977849, 0.0021155086839042335, 1.0]]
calculating the denominator = summing across the last dimension of the numerator (vocab_size)
the denominator is [[1.2350157969095403], [1.2282642975787637], [1.002377526568102]]
calculating the probabilities by dividing the numerator by the denominator
the final probabilities are [[0.18971228170607937, 0.8097062422216497, 0.0005814760722709904], [0.8141570197646114, 0.02835949019848497, 0.15748349003690373], [0.00026139640729463547, 0.0021104909356330272, 0.9976281126570723]]
the shape of the probabilities is (3, 3)


Cross-Entropy Loss

In [17]:
from src.utils.optimisation import cross_entropy_loss_one_hot, cross_entropy_loss_sparse

In [18]:
loss_one_hot = cross_entropy_loss_one_hot(probabilities, labels_one_hot)
loss_one_hot

1.7424716398775002

In [19]:
loss_sparse = cross_entropy_loss_sparse(probabilities, labels_sparse)
loss_sparse

1.7424716398775002