Imports

In [1]:
import numpy as np

Softmax

In [2]:
from src.modules.activations import softmax

In [3]:
big = np.array([1000.0, 999.0, 998.0])

In [4]:
softmax(big), softmax(big, subtract_max=True)

calculating the numerator = e^x for each value of x in the input tensor of scores
the nummerator is [1.         0.36787944 0.13533528]
calculating the denominator = summing across the last dimension of the numerator (vocab_size)
the denominator is [1.50321472]
calculating the numerator = e^x for each value of x in the input tensor of scores
the nummerator is [1.         0.36787944 0.13533528]
calculating the denominator = summing across the last dimension of the numerator (vocab_size)
the denominator is [1.50321472]


(array([0.66524096, 0.24472847, 0.09003057]),
 array([0.66524096, 0.24472847, 0.09003057]))

Cross-Entropy Loss

In [5]:
from src.utils.optimisation import cross_entropy_loss_one_hot, cross_entropy_loss_sparse

In [6]:
# Example with 3 samples and 3 classes

sample_1 = [0.70, 0.20, 0.10]
sample_2 = [0.10, 0.85, 0.05]
sample_3 = [0.60, 0.30, 0.10]

predictions = np.array([sample_1, sample_2, sample_3])
predictions, predictions.shape

(array([[0.7 , 0.2 , 0.1 ],
        [0.1 , 0.85, 0.05],
        [0.6 , 0.3 , 0.1 ]]),
 (3, 3))

In [7]:
# labels
labels_sparse = np.array([0, 1, 2])

labels_one_hot = np.array([
    [1, 0, 0],  # True class is index 0
    [0, 1, 0],  # True class is index 1
    [0, 0, 1]   # True class is index 2
])

labels_sparse.shape, labels_one_hot.shape

((3,), (3, 3))

In [9]:
loss_one_hot = cross_entropy_loss_one_hot(predictions, labels_one_hot)
loss_one_hot

0.9405929888101842

In [10]:
loss_sparse = cross_entropy_loss_sparse(predictions, labels_sparse)
loss_sparse

0.9405929888101842