Imports

In [1]:
import numpy as np

Old

In [2]:
# Example with 4 inputs and 5 features (tokens)

input_1 = 'The cat sat on the'
input_2 = 'There once was a dog'
input_3 = 'A tree in the park'
input_4 = 'In all of my life'

input = np.array([input_1, input_2, input_3, input_4])  # shape (4,)
input, input.shape

(array(['The cat sat on the', 'There once was a dog', 'A tree in the park',
        'In all of my life'], dtype='<U20'),
 (4,))

In [3]:
# Tokenize
import sys
sys.path.append("..")
from src.modules.tokenization import split_whitespace

final_list = []

for sequence in input:
    token_list = []
    tokens = split_whitespace(sequence)
    for token in tokens:
        token_list.append(token)
    final_list.append(token_list)

input_tokens = np.array(final_list) # shape (4,5)
input_tokens, input_tokens.shape 

ImportError: cannot import name 'split_whitespace' from 'src.modules.tokenization' (c:\Users\Satyam\Downloads\transformer-from-scratch\notebooks\..\src\modules\tokenization.py)

In [4]:
# Build vocabulary
from src.modules.tokenization import build_vocabulary

input_text = " ".join([input_1, input_2, input_3, input_4])
input_text

vocab = build_vocabulary(input_text)
vocab

{'the': 0,
 'The': 1,
 'cat': 2,
 'sat': 3,
 'on': 4,
 'There': 5,
 'once': 6,
 'was': 7,
 'a': 8,
 'dog': 9,
 'A': 10,
 'tree': 11,
 'in': 12,
 'park': 13,
 'In': 14,
 'all': 15,
 'of': 16,
 'my': 17,
 'life': 18}

In [ ]:
# Create input data
tokens = split_whitespace(text)          # list of ~40 strings
ids = [vocab[t] for t in tokens]         # list of ~40 ints
input_ids = np.array(ids).reshape(4, 10) # shape (batch, seq_len)
input_ids

Simple Text Example

In [5]:
text = "Disposal barbecues have been temporarily banned from sale over fears they pose a significant risk to the public as drought and heatwave conditions continue to grip the UK. It was the most extensive use of the system to date apparently"

In [6]:
# Build vocabulary
from src.modules.tokenization import build_vocabulary

vocab = build_vocabulary(text)
vocab

{'the': 0,
 'to': 1,
 'Disposal': 2,
 'barbecues': 3,
 'have': 4,
 'been': 5,
 'temporarily': 6,
 'banned': 7,
 'from': 8,
 'sale': 9,
 'over': 10,
 'fears': 11,
 'they': 12,
 'pose': 13,
 'a': 14,
 'significant': 15,
 'risk': 16,
 'public': 17,
 'as': 18,
 'drought': 19,
 'and': 20,
 'heatwave': 21,
 'conditions': 22,
 'continue': 23,
 'grip': 24,
 'UK.': 25,
 'It': 26,
 'was': 27,
 'most': 28,
 'extensive': 29,
 'use': 30,
 'of': 31,
 'system': 32,
 'date': 33,
 'apparently': 34}

In [9]:
#Create inputs
from src.modules.tokenization import create_inputs

input_ids = create_inputs(text=text, vocab=vocab, seq_len=10)
input_ids, input_ids.shape

(array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16,  1,  0, 17, 18, 19],
        [20, 21, 22, 23,  1, 24,  0, 25, 26, 27],
        [ 0, 28, 29, 30, 31,  0, 32,  1, 33, 34]]),
 (4, 10))

In [10]:
# Linear layer / weight matrix is 10 x 34 (mapping 10 input features to 34 output classes)
weights = np.random.randn(10, 34)
bias = np.zeros(34)

input_ids.shape, weights.shape, bias.shape

((4, 10), (10, 34), (34,))

In [11]:
# Output has 4 inputs and 34 classes, so the shape of the output is (4, 34)
# The labels must match the number of inputs, so we have 4 labels, one for each input.
# The labels can be represented in two ways: sparse (as integers) or one-hot encoded (as binary vectors).
labels_sparse = np.arange(34)
labels_one_hot = np.eye(34)[:4]

labels_sparse.shape, labels_one_hot.shape

((34,), (4, 34))

Linear Layer

In [12]:
from src.modules.feedforward import linear_layer

In [13]:
input_ids.shape, weights.shape, bias.shape

((4, 10), (10, 34), (34,))

In [14]:
logits = linear_layer(input_ids, weights, bias)
logits, logits.shape

(array([[ -11.08294268,   11.79687826,   28.79212386,  -13.69317096,
          -16.78869351,   26.6862058 ,   15.81238444,    6.70662411,
           -9.44666981,   -1.66388083,    8.86783963,   18.91613169,
          -25.51536762,  -52.97987039,   12.02405058,   -4.52302683,
          -11.06803736,   -6.35910521,  -17.44488142,   26.67708561,
           21.4393677 ,    5.36804234,   26.85662124,    5.11947498,
          -34.77702432,  -17.29121225,    4.10513754,   36.56826784,
           -6.19655726,   -6.45513787,  -41.4088395 ,   14.86196401,
          -49.14427602,   14.58005281],
        [  13.5720568 ,  -36.1603591 ,   10.08923871,  -49.51371703,
          -49.16317255,   86.0089005 ,  -14.9479653 ,  -26.72915233,
          -19.26847144,   16.38595548,   -7.21678326,   -1.0191561 ,
          -61.43577691, -115.00998887,   16.84498635,  -12.96357663,
           -2.85265014,  -26.65472991,  -67.37007875,   34.22931929,
           -6.14303161,   14.7021867 ,  107.38141787,   16.6044

Softmax

In [15]:
from src.modules.activations import softmax

In [16]:
probs = softmax(logits)

calculating the numerator = e^x for each value of x in the input tensor of scores
the numerator is [[2.0199574280951876e-21, 1.7455094131643884e-11, 0.0004196271523122128, 1.4850274379517518e-22, 6.719951141817239e-24, 5.108283439161023e-05, 9.679086523842524e-10, 1.0746150219387899e-13, 1.0374483724954271e-20, 2.488793149733447e-17, 9.32946810395097e-13, 2.1566251996303257e-08, 1.0899829440677946e-27, 1.2874717327155331e-39, 2.1906948166770844e-11, 1.4265187097934864e-18, 2.050291040545408e-21, 2.2744624120264403e-19, 3.486481177076817e-24, 5.0619067438854005e-05, 2.689070287935995e-07, 2.817826378339932e-14, 6.0573891127807705e-05, 2.197671617823644e-14, 1.035459953392239e-31, 4.065603287018558e-24, 7.969694020426816e-15, 1.0, 2.675915775983425e-19, 2.0661997774197463e-19, 1.3644969516989816e-34, 3.7417263725052706e-10, 5.963691566881896e-38, 2.82253636735079e-10], [1.8159844997263654e-41, 4.577183669326218e-63, 5.578834294432389e-43, 7.266222274724014e-69, 1.0316875948239384e-68, 5.

In [25]:
pred_ids = np.argmax(probs, axis=1)   # shape (4,)
pred_p = np.max(probs, axis=1)        # the actual probabilities

id_to_token = {i: tok for tok, i in vocab.items()}
pred_tokens = [id_to_token[i] for i in pred_ids]
pred_ids, pred_tokens

(array([27, 22,  5, 27]), ['was', 'conditions', 'been', 'was'])

Cross-Entropy Loss

In [17]:
from src.utils.optimisation import cross_entropy_loss_one_hot, cross_entropy_loss_sparse

In [18]:
loss_one_hot = cross_entropy_loss_one_hot(probs, labels_one_hot)
loss_one_hot

34.538776394910684

In [19]:
loss_sparse = cross_entropy_loss_sparse(probs, labels_sparse)
loss_sparse

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (34,) 